# NumPy

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

# Arreglos

In [7]:
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [9]:
arr = np.array(([1,2,3], [4,5,6]))

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr = np.array(([1,2,3], [4,5,6], [7,8,9]))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr = np.array([1,2,3,4,5,6], ndmin=3)

print(arr.ndim)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])


3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [15]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr = np.random.rand(3,3)

print(arr)

[[0.02151488 0.67231083 0.20917486]
 [0.87517504 0.64841543 0.98213325]
 [0.29849553 0.2581772  0.23710099]]


# Operaciones

In [20]:
arr1 = [1,2,3]
arr2 = [4,5,6]

arr3 = np.add(arr1, arr2)

print(arr3)

[5 7 9]


In [23]:
arr2 = [1,2,3]
arr1 = [4,5,6]

arr3 = np.subtract(arr1, arr2)

print(arr3)

[3 3 3]


# Agregacion

In [25]:
arr = [1, 5, 7]

media = np.mean(arr)

print(media)

4.333333333333333


In [26]:
arr = [1, 5, 7]

mediana = np.median(arr)

print(mediana)

5.0


In [27]:
arr = [1, 5, 7]

maximo = np.max(arr)

print(maximo)

7


In [28]:
arr = [1, 5, 7]

minimo = np.min(arr)

print(minimo)

1


# Indexacion

In [30]:
arr = np.array([1,2,3,4,5,6])

print(arr[0])

1


In [29]:
arr = np.array([1,2,3,4,5,6])

print(arr[-1])

6


In [31]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[1,2])

6


# Slicing